http:
  port: ':8080'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'localhost'
  port: '5432'
  db_name: 'deeznuts'
  username: 'postgres'
  migration_path: 'migrations/pg'
  migration_version: 1

token:
  time_to_live: "59m"

pusher:
  url: "https://d6c76406-7cc0-4105-95fc-6329a03549ae.pushnotifications.pusher.com/publish_api/v1/instances/d6c76406-7cc0-4105-95fc-6329a03549ae/publishes"
  api_token: "4ADD87428FB2819A82FFBAD97709CC9AA0DFE2EE0B6E41A320625D5CAF4FA401"
